---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgC3frzmelnusqsLIxrpN9Iq6z/laxGRNqDOsQkFwhOpTRnMkTTmI9JH16F3rv5hCRla2W5jgbFLw0MZKUhg+xsLry3sbBqDpWm//nafH5KpB57gmXZJ19wMd5UWuXohHY/BQxlqPmgy6kROGpP/Jp0nZvAe7v8SECWCcoQnL26JZTj2C6DHS4UnkjNUHCK6C2mHb3wKY9iV0fj0ovL266JpsyTviOJn5rzB24cZGB8kXESG2X/2G+VNSaLnqnJQxIOJf2Tl0kY2NNlo5JFTSlmzE60Oz1C8m68WKlR1wEcvNmuxy4tHWm/Qsf9vH2Pvs9B3XtL8CFTh0eO9rOc6Tzp7zEBhPP7cH8bStWHTKbLj8CG/8UzzTHZUgF/qvjOrChqMEn991J0d9XAu4qieOzhmdcaT5r+EWgVysyn80XaOWw2zZVIToo2LF/S2rJtDUntRmzY29MreI8I/EDY+59Nn7WzilLMPIuIme5S7qdKnXNmDNkqsPIRDmQ4Zfc8QZ3F1iIMqoU0dxDWn+X8LuUb8KxGZBgFTpm26crBH6ipIljLsqlwkvkCo10XnNuNJ580vyy++F7Qul08ia/Bb5V4bvx2BPe+yWZEzcrMMJTfOddbU4PcaXPf4vVYknbuJ8A1VW9ntVgPMwf8mVGf3R/ZAL4y71lwRjBriMWrdJQ4Zy9DMdujGcgTKJQFaRDcfRJBG+OZOVHhtFBdb+Y+z4zrMKfHM0nGfPXJ1kA4oBP1+4psunt/VwsvOahApgxL0ERxQteJvKTAb3wxaecSQb2vyz3+RrJUMC2yNZrhySjWOzD77fhVCRfp+zaBLohlUqTGMgvBS8iJA2U9A7YC8UfxGI3J62dRTWBGsAqr2blAdTzyRwbjQDp3KUtAG2wIe9x5ACFzkogzJXCQ2FQbAryX5fJH6mjf0R3cYuZLJ33D4
  template:
    metadata:
      name: cloudflared-credentials
      namespace: default
    type: Opaque
