---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: strava-credentials
  namespace: default
spec:
  encryptedData:
    STRAVA_CLIENT_ID: AgCxjWPGua+SDkYepfyybGNSn0EpIMpY6MKeOzn5ln37s0+Q3aDP1dfRNgt50rj5xmszocc7NOlByxCK3IAoJEG2TzdtpEwhM7Wu2ubNKB+DBJvFJD7wWNIuHLDXVrw2xR0WMzqAl8av2U9U9Hm0BuG3I2TgO9MgF/JPgq0w0CROrqshEYKcfqRjbBUDhR8UHBbzQwe2tMZbtjeolp+HnJUQ5kQUupw3Q9JCPqfRaitQva9WokGjxgSaOlUr/Ih76gyFJlKnR84Kw0YaCzDilA3kKI9KfrVXe5dvqsL0DvGwdnzpxrjvRPWNUEOl+YTgb3Pmtl5Io6CRljkYISXJISbg4KsqyjmPwQ1mJAg6GNFtLS2L3MaAHYtHB4m/GsurYKpxXvTTQhqtMpVSNAMMnfsDYgJ9iUha8yQ6WJJOVQh8i++thI7gPimRwcDKmTpS+J+y81tsmv7SqFj7ew1ykvu81dsbnBAGixKRaF5hgHTKcCKbXChV2yOsoV+eyEMKgVtbOT9eguyMgPb2x9C77efRNe54hdSm0Hdr3wlGk/0IonUp6ARBx4mTc9PtGxnLcXbtEHCuF9ZAiCeV7NwIKxuzAgj95EE9fwzwnw8FLIbGla8Uym0D4LTz5CD5o6R0EdgLus4lWTa/5hcLWIlAc8rySVHQv50mgjSQ+LsfNK/fZD3SyI/4mZbA7+2FJCI/BPttWyI5gg==
    STRAVA_CLIENT_SECRET: AgCxxcZuIzWu4sNW40XcgoFAKn8iwG1efg+fcreF4x4wdA2BWX9z9TN9o479tK+LrCXlBL0hTTDUA7auGbs3JLaEuDVN7+o3q0Aptz3PfkurnnrsiMMv5FUVod7hQRTk4UZPoF0Qdh/FauqTuyU6iTHgRES4JfST7k68ir+Rwz3KqyoMruSMIkJkhxQObYHqRSdXmpfmDrkYk5cVm4XQvJP/JLH+n2feLp4ViQ33XFpT+4qRwniKr1BOShsiIUHNZxQIM8v6EqTks+v9VLwB8SQbY5NxDKG/DaSEy7BstLt2fcaVyySMHSG36UtYoOKU9/lMlQymovkk0z8UyQ7jJszfe0tesP47kdneR0zC6K4744azm01R6FCZS7/4xMBoEfePJk3U7YEf3g6Bd+rtysbzO7l1YMbPc5V+15R0qYeG3/5G5BzmY/nCWTNwvH6Lv7F6Kw6oRxKb2hm5uHnau0iQKClhXH+tPLb48zyBMwcIL2VqS+UwMvslLjf+Rk8tEcf5KTSXkQasoRqXQUsHtrx2tqpjdjmo9i2yUO8xkNI4PgEoL1Jya24CVyb7XhgdC8GaKI0Q8HmkzeKy3gfEaNggy5D+fJUGrkoY1iIgm+7qnYyhNg0RMbiSzMEfKVFxGSCSEGLfSCMNzLouuxikAgrFpvOR+bqcSHPjFkwbSYkxjeDa8DhHwCGXi8eurHigoFwMpGK5hJ4qNgFM+UJcrTZQ8xV+5i/+FfDBiA0iyrDXIixC/nJWREtn
  template:
    metadata:
      name: strava-credentials
      namespace: default
    type: Opaque
